apiVersion: apps/v1
kind: Deployment
metadata:
  name: miyo-backend-user-deployment
  labels:
    app: miyo-backend-user
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: miyo-backend-user
  template:
    metadata:
      labels:
        app: miyo-backend-user
    spec:
      imagePullSecrets:
        - name: miyobackend
      containers:
      - name: miyo-backend-user
        image: contest90.kr.ncr.ntruss.com/contest90-backend:user-1.0
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_HOST
          value: "user-mysql-service"
        - name: DB_NAME
          value: "user_db"
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: BACKEND_URL
          valueFrom:
            secretKeyRef:
              name: url-secret
              key: url
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: user-mysql-secret
              key: root_password
        - name: MAIL_PW
          valueFrom:
            secretKeyRef:
              name: mail-secret
              key: mail_pw
        - name: NCP_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: ncp-secret
              key: ak
        - name: NCP_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: ncp-secret
              key: sk
        - name: NCP_BUCKET_NAME
          value: contest90-image-bucket



