apiVersion: apps/v1
kind: Deployment
metadata:
  name: miyo-backend-contest
  labels:
    app: miyo-backend-contest
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: miyo-backend-contest
  template:
    metadata:
      labels:
        app: miyo-backend-contest
    spec:
      imagePullSecrets:
        - name: miyobackend
      containers:
      - name: miyo-backend
        image: contest90.kr.ncr.ntruss.com/contest90-backend:challenge-1.0
        ports:
        - containerPort: 8080
        env:

        # JWT Configuration
        - name: jwtSecret
          valueFrom:
            secretKeyRef:
              name: jwtsecret-secret
              key: k

        # User Service Configuration
        - name: USER_SERVICE_URL
          value: "http://ing-default-samplealbing-bcdf6-110164755-b48ba1cb3cc4.kr.lb.naverncp.com"

        # NCP Object Storage Configuration
        - name: NCP_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: ncp-secret
              key: ak
        - name: NCP_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: ncp-secret
              key: sk
        - name: NCP_BUCKET_NAME
          value: "contest90-image-bucket"
        - name: NCP_DIRECTORY
          value: "generate/"

        # Gemini AI Configuration
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-secret
              key: api-key
        - name: GEMINI_MODEL
          valueFrom:
            secretKeyRef:
              name: gemini-secret
              key: api-url

        # Redis Configuration
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"

        # MySQL Configuration
        - name: MYSQL_HOST
          value: "user-mysql-service"
        - name: DB_NAME
          value: "challenge_db"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: challenge-db-password
