apiVersion: apps/v1
kind: Deployment
metadata:
  name: miyo-backend-posts-deployment
  labels:
    app: miyo-backend-posts
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: miyo-backend-posts
  template:
    metadata:
      labels:
        app: miyo-backend-posts
    spec:
      imagePullSecrets:
        - name: miyobackend
      containers:
      - name: miyo-backend-posts
        image: contest90.kr.ncr.ntruss.com/contest90-backend:posts-1.0
        ports:
        - containerPort: 8080
        env:
        # Write DB Configuration
        - name: WRITE_MYSQL_HOST
          value: "post-write-mysql-service"
        - name: WRITE_DB_NAME
          value: "post_write_db"
        - name: WRITE_MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: post-write-mysql-secret
              key: root_password

        # Read DB Configuration
        - name: READ_MYSQL_HOST
          value: "post-read-mysql-service"
        - name: READ_DB_NAME
          value: "post_read_db"
        - name: READ_MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: post-read-mysql-secret
              key: root_password

        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"

        # JWT Configuration
        - name: jwtSecret
          valueFrom:
            secretKeyRef:
              name: jwtsecret-secret
              key: k

        # User Service Configuration
        - name: USER_SERVICE_URL
          value: "http://ing-default-samplealbing-bcdf6-110164755-b48ba1cb3cc4.kr.lb.naverncp.com"
