name: CI/CD Pipeline for Spring Boot on NCP

on:
  push:
    branches:
      - main
      - '**/main'
  pull_request:
    branches:
      - main
      - '**/main'
      - '**/feature/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Docker Login to NCP Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.NCP_CONTAINER_REGISTRY_URL }}
          username: ${{ secrets.NCP_ACCESS_KEY }}
          password: ${{ secrets.NCP_SECRET_KEY }}

      - name: Build and push Docker image
        run: |
          # Get branch name and sanitize for Docker tag
          BRANCH_NAME=$(echo "${{ github.ref_name }}" | sed 's/[^a-zA-Z0-9._-]/-/g')
          
          # Create a dynamic tag using the branch name and short commit hash
          IMAGE_TAG="${BRANCH_NAME}-$(git rev-parse --short HEAD)"
          IMAGE_NAME="${{ secrets.NCP_CONTAINER_REGISTRY_URL }}/my-spring-app:${IMAGE_TAG}"

          echo "Building image with tag: ${IMAGE_TAG}"
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.NCP_K8S_KUBECONFIG_BASE64 }}" | base64 --decode > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy to Kubernetes
        run: |
          # Use the same dynamic tag for deployment
          BRANCH_NAME=$(echo "${{ github.ref_name }}" | sed 's/[^a-zA-Z0-9._-]/-/g')
          IMAGE_TAG="${BRANCH_NAME}-$(git rev-parse --short HEAD)"
          IMAGE_NAME="${{ secrets.NCP_CONTAINER_REGISTRY_URL }}/my-spring-app:${IMAGE_TAG}"
          
          echo "Deploying image: ${IMAGE_NAME}"

          # Replace the placeholder in the deployment YAML and apply it
          sed "s|__IMAGE_NAME__|${IMAGE_NAME}|g" k8s-deployment.yml | kubectl apply -f -
