name: CI/CD Pipeline for Spring Boot on NCP

on:
  push:
    branches:
      - main
      - '**/main'
      - '**/develop'
      - '**/feature/**'
  pull_request:
    branches:
      - main
      - '**/main'
      - '**/develop'
      - '**/feature/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
